config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end

  resources :users do
    resources :songs
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  get "/logout", to: "sessions#destroy"

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs
  
  validates :username, presence: true, uniqueness: true
  has_secure_password
  enum role: %w(default admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  # Make this method available to the views
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You are now logged in, #{user.username}."
      redirect_to user_songs_path(user_id: user.id)
    else
      flash[:error] = "We were unable to log you in."
      render :new # Render is fater than redirect_to
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    render :new
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    # Using the form_for method you will grab params[:song]
    # Song.create(params[:song])
    # This way is the secure way to do it in Rails 4
    song = Song.new(song_params)

    if song.save
      session[:most_recent_song_title] = song_params[:title]
      flash[:notice] = "#{song_params[:title]} added!"
    else
      flash[:error] = "Song could not be added."
    end

    redirect_to user_songs_path(song_params[:user_id])
  end

  # This is required in Rails 4 as a security measure
  #   to limit what form fields can be created/updated
  def edit
  end

  def update
    @song.update(song_params)
    redirect_to @song
  end

  def destroy
    @song.delete
    redirect_to user_songs_path(song_params[:user_id])
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end
  
  def song_params
    params.require(:song).permit(:title, :artist, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      flash[:notice] = "Welcome to MyJamz, #{user.username}!"
      redirect_to new_user_song_path(user_id: user.id)
    else
      flash[:error] = "Unable to create this account."
      render :new # Render is fater than redirect_to
    end
  end

  # Necessary to prevent XSS
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1>All Users</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "flash_#{type}" %>
  <% end %>
  <% if current_user %>
    <p>You are logged in as <%= current_user.username %>. |
    <%= link_to "Logout", logout_path %></p>
  <% else %>
    <p><%= link_to "Sign In", login_path %></p>
  <% end %>
  <%= yield %>
  <% if session[:most_recent_song_title] %>
    <p><strong>Newest song:</strong> <%= session[:most_recent_song_title] %></p>
  <% end %>
</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song, url: user_songs_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist %>
  <%= f.text_field :artist %><br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Ultimate Jamz</h1>
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "flash_#{type}" %>
<% end %>
<table>
  <caption>Songs</caption>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Artist</th>
      <td>&nbsp;</th>
      <td>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.id %></td>
        <td><%= link_to song.title, song %></td>
        <td><%= song.artist %>
        <td><%= link_to "edit", edit_user_song_path(song) %></td>
        <td><%= link_to "delete", user_song_path(song), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= link_to "New Song", new_user_song_path %></p>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1>Ultimate Jamz</h1>
<table>
  <caption>Song</caption>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Artist</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @song.id %></td>
        <td><%= @song.title %></td>
        <td><%= @song.artist %></td>
      </tr>
  </tbody>
</table>
<p><%= link_to "All Songs", user_songs_path(@song.user_id) %></p>

app/views/users/new.html.erb
<h1>Create An Account</h1>
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit "Create Account" %>
<% end %>